param(
    [string]$RepositoryRoot = (Resolve-Path (Join-Path $PSScriptRoot "../..")),
    [string]$OutputPath = (Join-Path $PSScriptRoot "Install_All.generated.sql")
)

$ErrorActionPreference = "Stop"
$sourceDirectories = @(
    "Code/00_Setup", "Code/01_Common", "Code/02_CurrentState", "Code/03_ObjectIndex",
    "Code/04_PlanCache", "Code/05_QueryStore", "Code/06_ExtendedEvents",
    "Code/07_Infrastructure", "Code/08_ServerHealth", "Code/09_VersionAdaptive"
)

$files = foreach ($directory in $sourceDirectories) {
    Get-ChildItem -Path (Join-Path $RepositoryRoot $directory) -Filter "*.sql" -File | Sort-Object Name
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("USE [DeineDatenbank];")
[void]$builder.AppendLine("GO")
[void]$builder.AppendLine()
[void]$builder.AppendLine("/* Generated from canonical source files. Do not edit this file directly. */")

foreach ($file in $files) {
    $relative = [IO.Path]::GetRelativePath($RepositoryRoot, $file.FullName).Replace('\','/')
    [void]$builder.AppendLine()
    [void]$builder.AppendLine("-- BEGIN SOURCE: $relative")
    $content = [IO.File]::ReadAllText($file.FullName, [Text.Encoding]::UTF8)
    $content = [Text.RegularExpressions.Regex]::Replace($content, '^\uFEFF?USE \[DeineDatenbank\];\r?\nGO\r?\n\r?\n', '')
    [void]$builder.AppendLine($content.TrimEnd())
    [void]$builder.AppendLine("-- END SOURCE: $relative")
}

[IO.File]::WriteAllText($OutputPath, $builder.ToString(), [Text.UTF8Encoding]::new($false))
Write-Host "Generated $OutputPath from $($files.Count) canonical SQL files."
