#!/usr/bin/env python3
"""Validate CurrentRequests literal ABI, shared selection and source isolation."""
from __future__ import annotations
import argparse
from pathlib import Path
import re
PROCEDURE_PATH=Path("Code/02_CurrentState/020_USP_CurrentRequests.sql")
TABLES={'#CurrentRequests_ResultTableMap': [('ResultName',
                                      'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL PRIMARY KEY'),
                                     ('TargetTable',
                                      'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL UNIQUE')],
 '#CurrentRequests_SessionIdFilter': [('SessionId', 'smallint NOT NULL PRIMARY KEY')],
 '#CurrentRequests_StringFilter': [('FilterType',
                                    'varchar(20) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                   ('StringValue',
                                    'nvarchar(4000) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL')],
 '#CurrentRequests_Warnings': [('WarningId', 'int IDENTITY(1,1) NOT NULL PRIMARY KEY'),
                               ('SessionId', 'smallint NULL'),
                               ('RequestId', 'int NULL'),
                               ('DatabaseName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                               ('Code', 'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                               ('Message', 'nvarchar(2048) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL')],
 '#CurrentRequests_Result': [('SessionId', 'smallint NOT NULL'),
                             ('RequestId', 'int NOT NULL'),
                             ('RequestStatus', 'nvarchar(30) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('Command', 'nvarchar(32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('DatabaseId', 'smallint NULL'),
                             ('DatabaseName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('LoginName', 'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('OriginalLoginName', 'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('HostName', 'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ProgramName', 'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('IsToolBackgroundQuery', 'bit NOT NULL'),
                             ('ToolBackgroundRuleCode',
                              'varchar(64) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ToolBackgroundCategory',
                              'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ToolBackgroundDetection',
                              'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ToolBackgroundConfidence',
                              'varchar(16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('StartTime', 'datetime NULL'),
                             ('ElapsedMs', 'int NULL'),
                             ('CpuMs', 'int NULL'),
                             ('LogicalReads', 'bigint NULL'),
                             ('Reads', 'bigint NULL'),
                             ('Writes', 'bigint NULL'),
                             ('RowCount', 'bigint NULL'),
                             ('PercentComplete', 'real NULL'),
                             ('EstimatedCompletionTimeMs', 'bigint NULL'),
                             ('BlockingSessionId', 'smallint NULL'),
                             ('WaitType', 'nvarchar(120) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('WaitTimeMs', 'int NULL'),
                             ('LastWaitType', 'nvarchar(120) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('WaitResource', 'nvarchar(256) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('WaitingTaskCount', 'int NULL'),
                             ('MaxTaskWaitMs', 'bigint NULL'),
                             ('TaskWaitTypes', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('RequestedMemoryMb', 'decimal(19,2) NULL'),
                             ('GrantedMemoryMb', 'decimal(19,2) NULL'),
                             ('UsedMemoryMb', 'decimal(19,2) NULL'),
                             ('IdealMemoryMb', 'decimal(19,2) NULL'),
                             ('Dop', 'smallint NULL'),
                             ('ParallelWorkerCount', 'int NULL'),
                             ('TransactionIsolationLevel',
                              'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('OpenTransactionCount', 'int NULL'),
                             ('OpenResultsetCount', 'int NULL'),
                             ('TransactionId', 'bigint NULL'),
                             ('ConnectionId', 'uniqueidentifier NULL'),
                             ('SchedulerId', 'int NULL'),
                             ('TaskAddress', 'varbinary(8) NULL'),
                             ('NestLevel', 'int NULL'),
                             ('WorkloadGroupId', 'int NULL'),
                             ('WorkloadGroupName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ResourcePoolId', 'int NULL'),
                             ('ResourcePoolName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('StatementSqlHandle', 'varbinary(64) NULL'),
                             ('StatementContextId', 'bigint NULL'),
                             ('IsResumable', 'bit NULL'),
                             ('ExecutingManagedCode', 'bit NULL'),
                             ('ContextInfo', 'varbinary(128) NULL'),
                             ('ClientNetAddress', 'varchar(48) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('QueryHash', 'binary(8) NULL'),
                             ('QueryPlanHash', 'binary(8) NULL'),
                             ('SqlHandle', 'varbinary(64) NULL'),
                             ('PlanHandle', 'varbinary(64) NULL'),
                             ('SqlTextDatabaseId', 'int NULL'),
                             ('SqlTextObjectId', 'int NULL'),
                             ('SqlTextObjectNumber', 'smallint NULL'),
                             ('SqlTextIsEncrypted', 'bit NULL'),
                             ('ExecutionContextType',
                              'varchar(20) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ModuleDatabaseName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ModuleSchemaName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ModuleObjectName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ModuleType', 'char(2) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ModuleTypeDescription',
                              'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('ModuleFullName', 'nvarchar(776) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('HasStatementOffsets', 'bit NULL'),
                             ('IsStatementOffsetValid', 'bit NULL'),
                             ('StatementStartOffsetBytes', 'int NULL'),
                             ('StatementEndOffsetBytes', 'int NULL'),
                             ('StatementStartCharacter', 'int NULL'),
                             ('StatementEndCharacter', 'int NULL'),
                             ('StatementStartLine', 'int NULL'),
                             ('StatementEndLine', 'int NULL'),
                             ('CurrentStatementCharacterCount', 'bigint NULL'),
                             ('CurrentStatementBytes', 'bigint NULL'),
                             ('CurrentStatementIsTruncated', 'bit NULL'),
                             ('BatchTextCharacterCount', 'bigint NULL'),
                             ('BatchTextBytes', 'bigint NULL'),
                             ('BatchTextIsTruncated', 'bit NULL'),
                             ('CurrentStatement', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('BatchText', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('InputBufferEventType',
                              'nvarchar(256) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                             ('InputBufferParameterCount', 'smallint NULL'),
                             ('InputBufferCharacterCount', 'bigint NULL'),
                             ('InputBufferBytes', 'bigint NULL'),
                             ('InputBufferIsTruncated', 'bit NULL'),
                             ('InputBufferText', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_SnapshotStatus': [('SourceOrdinal', 'int NOT NULL'),
                                     ('SnapshotId', 'uniqueidentifier NOT NULL'),
                                     ('SourceCode',
                                      'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('SourceObject',
                                      'nvarchar(256) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('CapturedAtUtc', 'datetime2(3) NOT NULL'),
                                     ('CompletedAtUtc', 'datetime2(3) NOT NULL'),
                                     ('StatusCode',
                                      'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('IsPartial', 'bit NOT NULL'),
                                     ('CapturedRowCount', 'bigint NOT NULL'),
                                     ('ErrorNumber', 'int NULL'),
                                     ('ErrorMessage',
                                      'nvarchar(2048) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_SourceSessions': [('session_id', 'smallint NOT NULL PRIMARY KEY'),
                                     ('is_user_process', 'bit NOT NULL'),
                                     ('login_name',
                                      'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('original_login_name',
                                      'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('host_name', 'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('program_name',
                                      'nvarchar(128) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_SourceRequests': [('session_id', 'smallint NOT NULL'),
                                     ('request_id', 'int NOT NULL'),
                                     ('status', 'nvarchar(30) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('command',
                                      'nvarchar(32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('database_id', 'smallint NOT NULL'),
                                     ('start_time', 'datetime NOT NULL'),
                                     ('total_elapsed_time', 'int NOT NULL'),
                                     ('cpu_time', 'int NOT NULL'),
                                     ('logical_reads', 'bigint NOT NULL'),
                                     ('reads', 'bigint NOT NULL'),
                                     ('writes', 'bigint NOT NULL'),
                                     ('row_count', 'bigint NOT NULL'),
                                     ('percent_complete', 'real NOT NULL'),
                                     ('estimated_completion_time', 'bigint NOT NULL'),
                                     ('blocking_session_id', 'smallint NULL'),
                                     ('wait_type', 'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('wait_time', 'int NOT NULL'),
                                     ('last_wait_type',
                                      'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('wait_resource',
                                      'nvarchar(256) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('dop', 'int NOT NULL'),
                                     ('parallel_worker_count', 'int NULL'),
                                     ('transaction_isolation_level', 'smallint NOT NULL'),
                                     ('open_transaction_count', 'int NOT NULL'),
                                     ('open_resultset_count', 'int NOT NULL'),
                                     ('transaction_id', 'bigint NOT NULL'),
                                     ('scheduler_id', 'int NULL'),
                                     ('task_address', 'varbinary(8) NULL'),
                                     ('nest_level', 'int NOT NULL'),
                                     ('group_id', 'int NOT NULL'),
                                     ('statement_sql_handle', 'varbinary(64) NULL'),
                                     ('statement_context_id', 'bigint NULL'),
                                     ('is_resumable', 'bit NOT NULL'),
                                     ('executing_managed_code', 'bit NOT NULL'),
                                     ('context_info', 'varbinary(128) NULL'),
                                     ('query_hash', 'binary(8) NULL'),
                                     ('query_plan_hash', 'binary(8) NULL'),
                                     ('sql_handle', 'varbinary(64) NULL'),
                                     ('plan_handle', 'varbinary(64) NULL'),
                                     ('statement_start_offset', 'int NULL'),
                                     ('statement_end_offset', 'int NULL')],
 '#CurrentRequests_SourceConnections': [('session_id', 'int NULL'),
                                        ('connection_id', 'uniqueidentifier NOT NULL PRIMARY KEY'),
                                        ('client_net_address',
                                         'varchar(48) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                        ('net_transport',
                                         'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                        ('protocol_type',
                                         'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                        ('encrypt_option',
                                         'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                        ('auth_scheme',
                                         'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL')],
 '#CurrentRequests_SourceWaitingTasks': [('waiting_task_address', 'varbinary(8) NOT NULL'),
                                         ('session_id', 'smallint NULL'),
                                         ('exec_context_id', 'int NULL'),
                                         ('wait_duration_ms', 'bigint NOT NULL'),
                                         ('wait_type',
                                          'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                         ('blocking_session_id', 'smallint NULL'),
                                         ('resource_description',
                                          'nvarchar(3072) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_SourceMemoryGrants': [('session_id', 'smallint NOT NULL'),
                                         ('request_id', 'int NOT NULL'),
                                         ('requested_memory_kb', 'bigint NOT NULL'),
                                         ('granted_memory_kb', 'bigint NULL'),
                                         ('used_memory_kb', 'bigint NULL'),
                                         ('ideal_memory_kb', 'bigint NULL')],
 '#CurrentRequests_SourceTasks': [('task_address', 'varbinary(8) NOT NULL PRIMARY KEY'),
                                  ('task_state',
                                   'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                  ('session_id', 'smallint NULL'),
                                  ('request_id', 'int NULL'),
                                  ('exec_context_id', 'int NULL'),
                                  ('scheduler_id', 'int NULL'),
                                  ('worker_address', 'varbinary(8) NULL')],
 '#CurrentRequests_SourceSchedulers': [('scheduler_id', 'int NOT NULL PRIMARY KEY'),
                                       ('scheduler_address', 'varbinary(8) NOT NULL'),
                                       ('parent_node_id', 'int NOT NULL'),
                                       ('status',
                                        'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                       ('is_online', 'bit NOT NULL'),
                                       ('is_idle', 'bit NOT NULL'),
                                       ('current_tasks_count', 'int NOT NULL'),
                                       ('runnable_tasks_count', 'int NOT NULL'),
                                       ('current_workers_count', 'int NOT NULL'),
                                       ('active_workers_count', 'int NOT NULL'),
                                       ('work_queue_count', 'bigint NOT NULL'),
                                       ('pending_disk_io_count', 'int NOT NULL'),
                                       ('load_factor', 'int NOT NULL')],
 '#CurrentRequests_SourceSessionTransactions': [('session_id', 'int NOT NULL'),
                                                ('transaction_id', 'bigint NOT NULL'),
                                                ('is_user_transaction', 'bit NOT NULL'),
                                                ('is_local', 'bit NOT NULL'),
                                                ('is_enlisted', 'bit NOT NULL'),
                                                ('is_bound', 'bit NOT NULL'),
                                                ('open_transaction_count', 'int NOT NULL')],
 '#CurrentRequests_SourceActiveTransactions': [('transaction_id', 'bigint NOT NULL PRIMARY KEY'),
                                               ('transaction_begin_time', 'datetime NOT NULL'),
                                               ('transaction_type', 'int NOT NULL'),
                                               ('transaction_state', 'int NOT NULL')],
 '#CurrentRequests_SourceDatabaseTransactions': [('transaction_id', 'bigint NOT NULL'),
                                                 ('database_id', 'int NOT NULL'),
                                                 ('database_transaction_log_bytes_used', 'bigint NOT NULL'),
                                                 ('database_transaction_log_bytes_reserved',
                                                  'bigint NOT NULL')],
 '#CurrentRequests_SourceTempDbSessionUsage': [('session_id', 'smallint NOT NULL PRIMARY KEY'),
                                               ('user_objects_alloc_page_count', 'bigint NOT NULL'),
                                               ('user_objects_dealloc_page_count', 'bigint NOT NULL'),
                                               ('internal_objects_alloc_page_count', 'bigint NOT NULL'),
                                               ('internal_objects_dealloc_page_count', 'bigint NOT NULL')],
 '#CurrentRequests_SourceTempDbTaskUsage': [('session_id', 'smallint NOT NULL'),
                                            ('request_id', 'int NOT NULL'),
                                            ('exec_context_id', 'int NOT NULL'),
                                            ('user_objects_alloc_page_count', 'bigint NOT NULL'),
                                            ('user_objects_dealloc_page_count', 'bigint NOT NULL'),
                                            ('internal_objects_alloc_page_count', 'bigint NOT NULL'),
                                            ('internal_objects_dealloc_page_count', 'bigint NOT NULL')],
 '#CurrentRequests_SourceWorkloadGroups': [('group_id', 'int NOT NULL PRIMARY KEY'),
                                           ('name', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                           ('pool_id', 'int NOT NULL')],
 '#CurrentRequests_SourceResourcePools': [('pool_id', 'int NOT NULL PRIMARY KEY'),
                                          ('name', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL')],
 '#CurrentRequests_SourceSqlText': [('SqlHandle', 'varbinary(64) NOT NULL PRIMARY KEY'),
                                    ('text', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                    ('dbid', 'int NULL'),
                                    ('objectid', 'int NULL'),
                                    ('number', 'smallint NULL'),
                                    ('encrypted', 'bit NULL')],
 '#CurrentRequests_SourceInputBuffer': [('session_id', 'smallint NOT NULL'),
                                        ('request_id', 'int NOT NULL'),
                                        ('event_type',
                                         'nvarchar(256) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                        ('parameters', 'smallint NULL'),
                                        ('event_info',
                                         'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_RequestContext': [('SnapshotId', 'uniqueidentifier NOT NULL'),
                                     ('CapturedAtUtc', 'datetime2(3) NOT NULL'),
                                     ('SessionId', 'smallint NOT NULL'),
                                     ('RequestId', 'int NOT NULL'),
                                     ('RequestStatus',
                                      'nvarchar(30) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('Command', 'nvarchar(32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('DatabaseId', 'smallint NULL'),
                                     ('DatabaseName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('StartTime', 'datetime NULL'),
                                     ('ElapsedMs', 'int NULL'),
                                     ('CpuMs', 'int NULL'),
                                     ('LogicalReads', 'bigint NULL'),
                                     ('Reads', 'bigint NULL'),
                                     ('Writes', 'bigint NULL'),
                                     ('RowCount', 'bigint NULL'),
                                     ('PercentComplete', 'real NULL'),
                                     ('EstimatedCompletionTimeMs', 'bigint NULL'),
                                     ('BlockingSessionId', 'smallint NULL'),
                                     ('WaitType', 'nvarchar(120) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('WaitTimeMs', 'bigint NULL'),
                                     ('WaitResource',
                                      'nvarchar(3072) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('ConnectionId', 'uniqueidentifier NULL'),
                                     ('ClientNetAddress',
                                      'varchar(48) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('NetTransport',
                                      'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('ProtocolType',
                                      'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('EncryptOption',
                                      'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('AuthScheme', 'nvarchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('TaskCount', 'int NULL'),
                                     ('WorkerCount', 'int NULL'),
                                     ('ExecutionContextCount', 'int NULL'),
                                     ('RunnableTaskCount', 'int NULL'),
                                     ('SuspendedTaskCount', 'int NULL'),
                                     ('SchedulerId', 'int NULL'),
                                     ('SchedulerStatus',
                                      'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('SchedulerParentNodeId', 'int NULL'),
                                     ('SchedulerRunnableTaskCount', 'int NULL'),
                                     ('SchedulerWorkQueueCount', 'bigint NULL'),
                                     ('SchedulerPendingDiskIoCount', 'int NULL'),
                                     ('SchedulerLoadFactor', 'int NULL'),
                                     ('TransactionId', 'bigint NULL'),
                                     ('TransactionBeginTime', 'datetime NULL'),
                                     ('TransactionAgeSeconds', 'bigint NULL'),
                                     ('TransactionType', 'int NULL'),
                                     ('TransactionState', 'int NULL'),
                                     ('IsUserTransaction', 'bit NULL'),
                                     ('IsLocalTransaction', 'bit NULL'),
                                     ('IsEnlistedTransaction', 'bit NULL'),
                                     ('IsBoundTransaction', 'bit NULL'),
                                     ('TransactionLogBytesUsed', 'bigint NULL'),
                                     ('TransactionLogBytesReserved', 'bigint NULL'),
                                     ('RequestedMemoryMb', 'decimal(19,2) NULL'),
                                     ('GrantedMemoryMb', 'decimal(19,2) NULL'),
                                     ('UsedMemoryMb', 'decimal(19,2) NULL'),
                                     ('IdealMemoryMb', 'decimal(19,2) NULL'),
                                     ('TempDbSessionNetMb', 'decimal(19,2) NULL'),
                                     ('TempDbRequestNetMb', 'decimal(19,2) NULL'),
                                     ('Dop', 'smallint NULL'),
                                     ('ParallelWorkerCount', 'int NULL'),
                                     ('WorkloadGroupId', 'int NULL'),
                                     ('WorkloadGroupName',
                                      'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('ResourcePoolId', 'int NULL'),
                                     ('ResourcePoolName',
                                      'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('QueryHash', 'binary(8) NULL'),
                                     ('QueryPlanHash', 'binary(8) NULL'),
                                     ('SqlHandle', 'varbinary(64) NULL'),
                                     ('PlanHandle', 'varbinary(64) NULL'),
                                     ('StatementSqlHandle', 'varbinary(64) NULL'),
                                     ('StatementContextId', 'bigint NULL'),
                                     ('ModuleFullName',
                                      'nvarchar(776) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                     ('IsCurrent', 'bit NOT NULL'),
                                     ('StatusCode',
                                      'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                     ('IsPartial', 'bit NOT NULL'),
                                     ('EvidenceBoundary',
                                      'nvarchar(512) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_Statements': [('SnapshotId', 'uniqueidentifier NOT NULL'),
                                 ('SessionId', 'smallint NOT NULL'),
                                 ('RequestId', 'int NOT NULL'),
                                 ('SourceCode', 'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                 ('CapturedAtUtc', 'datetime2(3) NOT NULL'),
                                 ('HasStatementOffsets', 'bit NULL'),
                                 ('IsStatementOffsetValid', 'bit NULL'),
                                 ('StartOffsetBytes', 'int NULL'),
                                 ('EndOffsetBytes', 'int NULL'),
                                 ('StartCharacter', 'int NULL'),
                                 ('EndCharacter', 'int NULL'),
                                 ('StartLine', 'int NULL'),
                                 ('EndLine', 'int NULL'),
                                 ('CharacterCount', 'bigint NULL'),
                                 ('Bytes', 'bigint NULL'),
                                 ('IsTruncated', 'bit NOT NULL'),
                                 ('StatusCode', 'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                 ('OmissionReason',
                                  'nvarchar(512) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                 ('Text', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_Batches': [('SnapshotId', 'uniqueidentifier NOT NULL'),
                              ('SessionId', 'smallint NOT NULL'),
                              ('RequestId', 'int NOT NULL'),
                              ('SourceCode', 'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                              ('CapturedAtUtc', 'datetime2(3) NOT NULL'),
                              ('SqlTextDatabaseId', 'int NULL'),
                              ('SqlTextObjectId', 'int NULL'),
                              ('SqlTextObjectNumber', 'smallint NULL'),
                              ('IsEncrypted', 'bit NULL'),
                              ('CharacterCount', 'bigint NULL'),
                              ('Bytes', 'bigint NULL'),
                              ('IsTruncated', 'bit NOT NULL'),
                              ('StatusCode', 'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                              ('OmissionReason', 'nvarchar(512) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                              ('Text', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_InputBuffers': [('SnapshotId', 'uniqueidentifier NOT NULL'),
                                   ('SessionId', 'smallint NOT NULL'),
                                   ('RequestId', 'int NOT NULL'),
                                   ('SourceCode',
                                    'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                   ('CapturedAtUtc', 'datetime2(3) NOT NULL'),
                                   ('EventType', 'nvarchar(256) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                   ('ParameterCount', 'smallint NULL'),
                                   ('CharacterCount', 'bigint NULL'),
                                   ('Bytes', 'bigint NULL'),
                                   ('IsTruncated', 'bit NOT NULL'),
                                   ('StatusCode',
                                    'varchar(40) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL'),
                                   ('OmissionReason',
                                    'nvarchar(512) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                   ('Text', 'nvarchar(max) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')],
 '#CurrentRequests_ModuleLookup': [('SqlTextDatabaseId', 'int NOT NULL'),
                                   ('SqlTextObjectId', 'int NOT NULL'),
                                   ('ModuleDatabaseName',
                                    'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                   ('ModuleSchemaName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                   ('ModuleObjectName', 'sysname COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                   ('ModuleType', 'char(2) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                   ('ModuleTypeDescription',
                                    'nvarchar(60) COLLATE SQL_Latin1_General_CP1_CS_AS NULL'),
                                   ('ModuleFullName',
                                    'nvarchar(776) COLLATE SQL_Latin1_General_CP1_CS_AS NULL')]}
PARAMETERS=['@SessionIds', '@EigeneSessionsModus', '@AktuelleSessionEinbeziehen', '@SystemSessionsEinbeziehen', '@ToolHintergrundabfragenEinbeziehen', '@NurBlockierte', '@NurMitWait', '@MinLaufzeitSekunden', '@MinCpuMs', '@MinLogicalReads', '@LoginNames', '@LoginNamePattern', '@HostNames', '@HostNamePattern', '@ProgramNames', '@ProgramNamePattern', '@DatabaseNames', '@DatabaseNamePattern', '@HighImpactConfirmed', '@TextPattern', '@MitSqlText', '@GesamtenSqlTextEinbeziehen', '@InputBufferEinbeziehen', '@ModulInfoEinbeziehen', '@MaxSqlTextZeichen', '@MaxZeilen', '@Sortierung', '@ResultSetArt', '@ResultTablesJson', '@JsonErzeugen', '@Json', '@PrintMeldungen', '@Hilfe', '@ParentCurrentStateSnapshotId']
TOKEN_COUNTS={'Version      : 4.0.0': 1, 'Stand        : 2026-07-23': 1, 'SET LOCK_TIMEOUT 0;': 1, '4 AS [schemaVersion]': 1, '[SnapshotId]=@ParentCurrentStateSnapshotId': 17, '[ContractVersion]=2': 1, '[OwnerSessionId]=CONVERT(smallint,@@SPID)': 1, '@MaxZeilen < 0': 1, '@MaxSqlTextZeichen < 0': 1, 'WHERE [RowNumber] > @MaxZeilen;': 1, 'SET @HasMoreRows = 1;': 1, "@SourceTable=N'#CurrentRequests_Result'": 4, '@SourceTable=@ExportSourceTable': 1, "@MappingTable=N'#CurrentRequests_ResultTableMap'": 1, "WHERE [SourceCode]='INPUT_BUFFER'": 1, "WHERE [SourceCode]='REQUESTS'": 1, "WHEN N'requests' THEN N'#CurrentRequests_Result'": 1, "WHEN N'requestContext' THEN N'#CurrentRequests_RequestContext'": 1, "WHEN N'snapshotStatus' THEN N'#CurrentRequests_SnapshotStatus'": 1, "WHEN N'statements' THEN N'#CurrentRequests_Statements'": 1, "WHEN N'batches' THEN N'#CurrentRequests_Batches'": 1, "WHEN N'inputBuffers' THEN N'#CurrentRequests_InputBuffers'": 1, "WHEN N'warnings' THEN N'#CurrentRequests_Warnings'": 1, '@SqlTextErforderlich=1': 3, '@AktuelleSessionEinbeziehen = 1 OR [r].[session_id] <> @@SPID': 1}

def definitions(source:str)->dict[str,list[tuple[str,str]]]:
 result={}
 for m in re.finditer(r"CREATE TABLE \[(#CurrentRequests_[^]]+)\]\s*\((.*?)\n\s*\);",source,re.S):
  fields=[]
  for part in re.split(r",\s*(?=\[|PRIMARY KEY)",m[2].strip()):
   f=re.fullmatch(r"\s*\[([^]]+)\]\s+(.*?)\s*",part,re.S)
   if f:fields.append((f[1],re.sub(r"\s+"," ",f[2])))
  result[m[1]]=fields
 return result

def validate(source:str)->list[str]:
 errors=[]
 actual=definitions(source)
 if list(actual)!=list(TABLES):errors.append("TABLE_ORDER")
 for table,fields in TABLES.items():
  if actual.get(table)!=fields:errors.append("DDL:"+table)
 for token,count in TOKEN_COUNTS.items():
  if source.count(token)!=count:errors.append("BOUNDARY:"+token)
 p=re.findall(r"^\s*,?\s*(@\w+)\s+",source[source.find("CREATE OR ALTER"):source.find("\nAS\n")],re.M)
 if p!=PARAMETERS:errors.append("PARAMETERS")
 positions=[source.find("SET @HasMoreRows = 1"),source.find("DELETE FROM [Ranked]"),source.find("IF @ModulInfoEinbeziehen = 1"),source.find("IF @InputBufferEinbeziehen = 1",source.find("DELETE FROM [Ranked]")),source.find("EXEC [monitor].[InternalProjectUnicodeTextColumn]"),source.find("INSERT [#CurrentRequests_RequestContext]"),source.find("SELECT @RowCount = COUNT_BIG(*)"),source.find("IF @JsonErzeugen = 1")]
 if any(i<0 for i in positions) or positions!=sorted(positions):errors.append("SHARED_CAP_CONTEXT_ORDER")
 if source.find("CREATE TABLE [#CurrentRequests_Result]")>source.find("WITH NOWAIT"):errors.append("EARLY_DDL")
 if source.count("CROSS APPLY [monitor].[TVF_WaitTypeInfo]")!=3:errors.append("WAIT_PROJECTIONS")

 if source.find('EXEC [monitor].[InternalPrepareResultTables]')>source.find('INSERT [#CurrentRequests_SessionIdFilter]'):errors.append('EARLY_TABLE_MAPPING')
 if 'CONVERT(bigint, [r].[total_elapsed_time]) >= CONVERT(bigint, @MinLaufzeitSekunden) * 1000' not in source:errors.append('DURATION_BIGINT_BEFORE_MULTIPLY')
 return errors

def self_test(source:str)->int:
 assert not validate(source),validate(source)
 mutations=[]
 for table,fields in TABLES.items():
  start=source.index("CREATE TABLE ["+table+"]");end=re.search(r"\n\s*\);",source[start:]).start()+start
  block=source[start:end]
  for name,definition in fields:
   original="["+name+"] "+definition
   # SQL permits arbitrary whitespace; locate the entire exact declaration in its own block.
   match=re.search(r"\["+re.escape(name)+r"\]\s+"+r"\s+".join(re.escape(x) for x in definition.split()),block)
   assert match,(table,name)
   literal=match[0]
   variants=[literal.replace("["+name+"]","[ExampleWrong]",1),literal.replace(definition.split()[0],"sql_variant",1)]
   if 'COLLATE ' in literal:variants.append(literal.replace('SQL_Latin1_General_CP1_CS_AS','Latin1_General_100_CI_AS'))
   variants.append(literal.replace('NOT NULL','NULL',1) if 'NOT NULL' in literal else re.sub(r'\bNULL\b','NOT NULL',literal,count=1))
   for variant in variants:mutations.append(source[:start]+block[:match.start()]+variant+block[match.end():]+source[end:])
 for token in TOKEN_COUNTS:mutations.append(source.replace(token,'EXAMPLE_REMOVED',1))
 cap='WHERE [RowNumber] > @MaxZeilen;'
 mutations.append(source.replace(cap,'WHERE [RowNumber] >= @MaxZeilen;',1))
 mutations.append(source.replace(cap,'',1))
 for i,param in enumerate(PARAMETERS):
  declaration=re.search(r'^\s*,?\s*'+re.escape(param)+r'\s+',source,re.M)
  assert declaration,param
  mutations.append(source[:declaration.start()]+source[declaration.start():].replace(param,'@ExampleWrong',1))
 mutations.append(source.replace('CONVERT(bigint, @MinLaufzeitSekunden) * 1000','@MinLaufzeitSekunden * 1000',1))
 mutations.append(source.replace('CONVERT(bigint, [r].[total_elapsed_time])','[r].[total_elapsed_time]',1))
 start=source.index("    IF @StatusCode='AVAILABLE' AND @TableResultRequested=1")
 end=source.index('    CREATE TABLE [#CurrentRequests_SessionIdFilter]',start)
 block=source[start:end];moved=source[:start]+source[end:]
 place=moved.index('    CREATE TABLE [#CurrentRequests_Result]')
 mutations.append(moved[:place]+block+moved[place:])
 for i,mutation in enumerate(mutations):assert validate(mutation),f'undetected mutation {i}'
 return len(mutations)

def main()->int:
 p=argparse.ArgumentParser();p.add_argument('--repository-root',type=Path,default=Path('.'));p.add_argument('--self-test',action='store_true');args=p.parse_args()
 source=(args.repository_root/PROCEDURE_PATH).read_text(encoding='utf-8-sig')
 if args.self_test:
  count=self_test(source);print(f'Current Requests self-test passed: mutations={count} findings=0');return 0
 errors=validate(source)
 if errors:print('Current Requests contract failed: '+', '.join(errors));return 1
 print('Current Requests contract passed: tables=27 text_collations=99 public_fields=230 public_texts=66 findings=0');return 0
if __name__=='__main__':raise SystemExit(main())
